export const USUARIO_MUDANCA_REDE = "USUARIO_MUDANCA_REDE";
export const USUARIO_MUDANCA_ESTADO = "USUARIO_MUDANCA_ESTADO";

export const DB_LIMPAR_ACOES = "DB_LIMPAR_ACOES";
export const DB_SINCRONIZACAO_COMPLETA_INTERNET = "DB_SINCRONIZACAO_COMPLETA_INTERNET";
export const DB_SINCRONIZACAO_COMPLETA_CACHE = "DB_SINCRONIZACAO_COMPLETA_CACHE";
export const DB_SINCRONIZACAO_ERRO = "DB_SINCRONIZACAO_ERRO";

export const DB_OPERACOES_PENDENTES_VAZIA = "DB_OPERACOES_PENDENTES_VAZIA";
export const DB_OPERACOES_PENDENTES_ENVIADAS = "DB_OPERACOES_PENDENTES_ENVIADAS";
export const DB_OPERACOES_PENDENTES_ERRO = "DB_OPERACOES_PENDENTES_ERRO";

export const DB_SALVAR_COMPLETO_INTERNET = "DB_SALVAR_COMPLETO_INTERNET";
export const DB_SALVAR_COMPLETO_CACHE = "DB_SALVAR_COMPLETO_CACHE";
export const DB_SALVAR_ERROR = "DB_SALVAR_ERROR";

export const LOCALIZACAO_RASTREAMENTO_COMECAR = "LOCALIZACAO_RASTREAMENTO_COMECAR";
export const LOCALIZACAO_RASTREAMENTO_TERMINAR = "LOCALIZACAO_RASTREAMENTO_TERMINAR";
export const LOCALIZACAO_RASTREAMENTO_NOVAPOSICAO = "LOCALIZACAO_RASTREAMENTO_NOVAPOSICAO";
export const LOCALIZACAO_RASTREAMENTO_NAO_COMECOU = "LOCALIZACAO_RASTREAMENTO_NAO_COMECOU";

export const DB_CLEAR = "DB_CLEAR";

export const DB_SYNC_CACHE_EMPTY = "DB_SYNC_CACHE_EMPTY";
export const DB_SYNC_CACHE_OK = "DB_SYNC_CACHE_OK";
export const DB_SYNC_CACHE_ERROR = "DB_SYNC_CACHE_ERROR";

export const DB_SAVE_OK = "DB_SAVE_OK";
export const DB_SAVE_CACHE = "DB_SAVE_CACHE";
export const DB_SAVE_ERROR = "DB_SAVE_ERROR";
export const LOCATION_TRACK_START = "LOCATION_TRACK_START";
export const LOCATION_TRACK_UPDATE = "LOCATION_TRACK_UPDATE";
export const LOCATION_TRACK_END = "LOCATION_TRACK_END";
export const LOCATION_TRACK_NOT_STARTED = "LOCATION_TRACK_NOT_STARTED";
